# Generated by Django 4.0.4 on 2022-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('limiteInferior', models.FloatField()),
                ('limiteSuperior', models.FloatField()),
                ('coeficienteGrado3', models.FloatField()),
                ('coeficienteGrado2', models.FloatField()),
                ('coeficienteGrado1', models.FloatField()),
                ('coeficienteGrado0', models.FloatField()),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
