# Generated by Django 4.0.4 on 2022-05-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plantas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plantas',
            new_name='Planta',
        ),
    ]
