# Generated by Django 4.0.4 on 2022-05-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantas', '0002_rename_plantas_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='factorDeConversion',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
